# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin  : "default"

# Site Settings
locale                 : "en-US"
title                  : "Tandis Salem"
title_separator        : "-"
subtitle               : "Ph.D. Student in Bioinformatics, UC Riverside"
name                   : "Tandis Salem"
description            : "Research on computational drug discovery and synergistic drug combinations"
url                    : "https://tandissalem.github.io"
baseurl                : ""   # leave blank unless site lives in a subfolder
repository             : "tandissalem/tandissalem.github.io"
teaser                 : 
logo                   : 
masthead_title         : 
words_per_minute       : 200

# Site Author
author:
  name             : "Tandis Salem"
  avatar           :   # add your portrait here if you have one
  bio              : "Ph.D. student in Bioinformatics at UC Riverside. Researching drug synergy prediction and computational drug discovery."
  location         : "California, USA"
  email            : "tsale010@ucr.edu" # replace with your actual email or leave blank
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tsale010@ucr.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tandissalem"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tandissalem/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: 

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tandissalem"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tandissalem/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes specific settings
search: true
search_full_content: true

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
